export const movies = [
  {
    adult: false,
    backdrop_path: '/fqv8v6AycXKsivp1T5yKtLbGXce.jpg',
    genre_ids: [878, 12, 28],
    genres: ['Action', 'Comedy'],
    id: 653346,
    original_language: 'en',
    original_title: 'Deadpool and Wolverine',
    overview:
      'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine. Everyone deserves a happy ending.',
    popularity: 4703.624,
    poster_path: '../../assets/images/kingdom-of-the-planet-of-the-apes.jpg',
    release_date: '2024-05-08',
    title: 'Kingdom of the Planet of the Apes',
    video: false,
    vote_average: 6.932,
    duration: '85 minutes',
    vote_count: 807,
    rating: '9 / 10',
  },
  {
    adult: false,
    backdrop_path: '/z121dSTR7PY9KxKuvwiIFSYW8cf.jpg',
    genre_ids: [10752, 28, 18],
    genres: ['Action', 'Thriller'],
    id: 929590,
    original_language: 'en',
    original_title: 'John Wick',
    overview:
      'John Wick is a former hitman grieving the loss of his true love. When his home is broken into, robbed, and his dog killed, he is forced to return to action to exact revenge.',
    popularity: 2418.019,
    poster_path: '../../assets/images/john-wick-fury.jpg',
    release_date: '2024-04-10',
    title: 'John Wick',
    video: false,
    vote_average: 7.1,
    duration: '100 minutes',
    vote_count: 1296,
    rating: '9 / 10',
  },
  {
    adult: false,
    backdrop_path: '/xRd1eJIDe7JHO5u4gtEYwGn5wtf.jpg',
    genre_ids: [878, 28, 12],
    genres: ['Action'],
    id: 823464,
    original_language: 'en',
    original_title: 'Transformers. One of the unstoppable force',
    overview:
      'The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but who once were friends bonded like brothers who changed the fate of Cybertron forever.',
    popularity: 1931.335,
    poster_path:
      '../../assets/images/transformers-one-the-unstoppable-force-1920x1080.jpg',
    release_date: '2024-03-27',
    title: 'Transformers: One of the unstoppable force',
    video: false,
    vote_average: 7.233,
    duration: '80 minutes',
    vote_count: 2519,
    rating: '9 / 10',
  },
  {
    adult: false,
    backdrop_path: '/oavbmL3iddJUmC8nQjL6bLHwAP4.jpg',
    genre_ids: [27, 53],
    genres: ['Adventure'],
    id: 719221,
    original_language: 'en',
    original_title: 'Disney Mufasa The Lion King',
    overview:
      'Simba, having become king of the Pride Lands, is determined for his cub to follow in his paw prints while the origins of his late father Mufasa are explored.',
    popularity: 1540.535,
    poster_path:
      '../../assets/images/disney-mufasa-the-lion-king-1920x1080.jpg',
    release_date: '2024-05-01',
    title: 'Disney Mufasa The Lion King',
    video: false,
    vote_average: 6.5,
    duration: '90 minutes',
    vote_count: 341,
    rating: '9 / 10',
  },
];
